### ISSUE TITLE
Rename Snakefile.txt to Snakefile

### ISSUE THREAD

**Issue by ok-lch** [romainsacchi/bw-repro#5]
## Current
Extracting `output.zip` and executing `snakemake -j 1 --use-conda` end up with an error:
```
❯ snakemake -j 1 --use-conda    
Error: no Snakefile found, tried Snakefile, snakefile, workflow/Snakefile, workflow/snakefile.
```

## Expected
It should read the Snakefile

## Solution
Rename `Snakefile.txt` to `Snakefile`

**Comment by tyrael147** [comment]
This has been corrected in `dev` branch
